/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unicesar.vista;

import java.awt.Color;
import co.edu.unicesar.modelo.*;
import co.edu.unicesar.persistencia.*;
import co.edu.unicesar.utilidades.Consola;
import java.awt.Component;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import co.edu.unicesar.modelo.Publicacion;
import co.edu.unicesar.utilidades.Interfaz;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author LENOVO
 */
public class PanelInsertar extends javax.swing.JPanel {

    /**
     * Creates new form PanelInsertar
     */
    public static ListaPublicacion modelo;
    public static Publicacion publicacion;
    FileWriter salvar;
    Interfaz util;
    ArchivoTxt archivo;

    public PanelInsertar() {
        initComponents();
        util = new Interfaz();
        archivo = new ArchivoTxt();
        audioLibro.setVisible(false);
        util.deshabilitarPanel(libro);
        util.deshabilitarPanel(audioLibro);
        modelo = new ListaPublicacion();
        
        deshabilitarTab();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        informacion = new javax.swing.JPanel();
        isbn = new javax.swing.JLabel();
        textIsbn = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        titulo = new javax.swing.JLabel();
        textTitulo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        autor = new javax.swing.JLabel();
        textAutor = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        textAnio = new javax.swing.JTextField();
        anio = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        tipo = new javax.swing.JLabel();
        boxTipo = new javax.swing.JComboBox<>();
        costo = new javax.swing.JLabel();
        textCosto = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        audioLibro = new javax.swing.JPanel();
        formato = new javax.swing.JLabel();
        textFormato = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        textDuracion = new javax.swing.JTextField();
        duracion = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        textPeso = new javax.swing.JTextField();
        peso = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        libro = new javax.swing.JPanel();
        noPag = new javax.swing.JLabel();
        textPag = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        edicion = new javax.swing.JLabel();
        textEdicion = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgMouseClicked(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("REGISTRAR LIBRO");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 34, -1, -1));

        botonRegistrar.setBackground(new java.awt.Color(43, 42, 77));
        botonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGISTRAR");

        javax.swing.GroupLayout botonRegistrarLayout = new javax.swing.GroupLayout(botonRegistrar);
        botonRegistrar.setLayout(botonRegistrarLayout);
        botonRegistrarLayout.setHorizontalGroup(
            botonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonRegistrarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        botonRegistrarLayout.setVerticalGroup(
            botonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        bg.add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 150, 40));

        informacion.setBackground(new java.awt.Color(255, 255, 255));
        informacion.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(43, 42, 77), 1, true), "INFORMACION", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        informacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                informacionMouseEntered(evt);
            }
        });

        isbn.setBackground(new java.awt.Color(255, 255, 255));
        isbn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        isbn.setText("ISBN");

        textIsbn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textIsbn.setForeground(new java.awt.Color(204, 204, 204));
        textIsbn.setText("Ingrese el isbn...");
        textIsbn.setBorder(null);
        textIsbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textIsbnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textIsbnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textIsbnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textIsbnMousePressed(evt);
            }
        });
        textIsbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textIsbnKeyTyped(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titulo.setText("TITULO");

        textTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textTitulo.setForeground(new java.awt.Color(204, 204, 204));
        textTitulo.setText("Ingrese el titulo...");
        textTitulo.setBorder(null);
        textTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textTituloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textTituloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textTituloMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textTituloMousePressed(evt);
            }
        });
        textTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTituloActionPerformed(evt);
            }
        });
        textTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textTituloKeyTyped(evt);
            }
        });

        autor.setBackground(new java.awt.Color(255, 255, 255));
        autor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        autor.setText("AUTOR");

        textAutor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textAutor.setForeground(new java.awt.Color(204, 204, 204));
        textAutor.setText("Ingrese el autor...");
        textAutor.setBorder(null);
        textAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textAutorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textAutorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textAutorMousePressed(evt);
            }
        });
        textAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAutorKeyTyped(evt);
            }
        });

        textAnio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textAnio.setForeground(new java.awt.Color(204, 204, 204));
        textAnio.setText("Ingrese el año pub...");
        textAnio.setBorder(null);
        textAnio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textAnioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textAnioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textAnioMousePressed(evt);
            }
        });
        textAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAnioKeyTyped(evt);
            }
        });

        anio.setBackground(new java.awt.Color(255, 255, 255));
        anio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        anio.setText("AÑO PUB");

        tipo.setBackground(new java.awt.Color(255, 255, 255));
        tipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tipo.setText("TIPO");

        boxTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Tipo", "Libro", "Audio Libro" }));
        boxTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boxTipoMousePressed(evt);
            }
        });
        boxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipoActionPerformed(evt);
            }
        });

        costo.setBackground(new java.awt.Color(255, 255, 255));
        costo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        costo.setText("COSTO");

        textCosto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textCosto.setForeground(new java.awt.Color(204, 204, 204));
        textCosto.setText("Ingrese el precio...");
        textCosto.setBorder(null);
        textCosto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textCostoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textCostoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textCostoMousePressed(evt);
            }
        });
        textCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCostoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout informacionLayout = new javax.swing.GroupLayout(informacion);
        informacion.setLayout(informacionLayout);
        informacionLayout.setHorizontalGroup(
            informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionLayout.createSequentialGroup()
                .addGroup(informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informacionLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(informacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(anio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, informacionLayout.createSequentialGroup()
                                .addGroup(informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(informacionLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jSeparator4))
                                    .addComponent(textAnio, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                                .addGap(204, 204, 204))
                            .addGroup(informacionLayout.createSequentialGroup()
                                .addGroup(informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(isbn)
                                    .addGroup(informacionLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(textIsbn))
                                .addGap(51, 51, 51)
                                .addGroup(informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(titulo)
                                    .addComponent(textTitulo)
                                    .addGroup(informacionLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(costo)
                                            .addComponent(jSeparator2)
                                            .addComponent(textCosto, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(autor)
                    .addComponent(textAutor)
                    .addGroup(informacionLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipo)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
        );
        informacionLayout.setVerticalGroup(
            informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(informacionLayout.createSequentialGroup()
                        .addComponent(costo)
                        .addGap(6, 6, 6)
                        .addComponent(textCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(informacionLayout.createSequentialGroup()
                        .addGroup(informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(informacionLayout.createSequentialGroup()
                                .addComponent(isbn)
                                .addGap(6, 6, 6)
                                .addComponent(textIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(informacionLayout.createSequentialGroup()
                                .addComponent(titulo)
                                .addGap(6, 6, 6)
                                .addComponent(textTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(informacionLayout.createSequentialGroup()
                                .addComponent(autor)
                                .addGap(6, 6, 6)
                                .addComponent(textAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(informacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(informacionLayout.createSequentialGroup()
                                .addComponent(tipo)
                                .addGap(3, 3, 3)
                                .addComponent(boxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(informacionLayout.createSequentialGroup()
                                .addComponent(anio)
                                .addGap(6, 6, 6)
                                .addComponent(textAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 580, 160));

        audioLibro.setBackground(new java.awt.Color(255, 255, 255));
        audioLibro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 36, 86)), "AUDIO LIBRO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        audioLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                audioLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                audioLibroMouseEntered(evt);
            }
        });

        formato.setBackground(new java.awt.Color(255, 255, 255));
        formato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        formato.setText("FORMATO");

        textFormato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textFormato.setForeground(new java.awt.Color(204, 204, 204));
        textFormato.setText("Ingrese el formato...");
        textFormato.setBorder(null);
        textFormato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textFormatoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textFormatoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textFormatoMousePressed(evt);
            }
        });
        textFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFormatoActionPerformed(evt);
            }
        });
        textFormato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFormatoKeyTyped(evt);
            }
        });

        textDuracion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textDuracion.setForeground(new java.awt.Color(204, 204, 204));
        textDuracion.setText("Ingrese la duracion...");
        textDuracion.setBorder(null);
        textDuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textDuracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textDuracionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textDuracionMousePressed(evt);
            }
        });
        textDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDuracionActionPerformed(evt);
            }
        });
        textDuracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textDuracionKeyTyped(evt);
            }
        });

        duracion.setBackground(new java.awt.Color(255, 255, 255));
        duracion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        duracion.setText("DURACION(SEG)");

        textPeso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textPeso.setForeground(new java.awt.Color(204, 204, 204));
        textPeso.setText("Ingrese el peso...");
        textPeso.setBorder(null);
        textPeso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textPesoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textPesoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textPesoMousePressed(evt);
            }
        });
        textPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPesoActionPerformed(evt);
            }
        });
        textPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPesoKeyTyped(evt);
            }
        });

        peso.setBackground(new java.awt.Color(255, 255, 255));
        peso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        peso.setText("PESO(MB)");

        javax.swing.GroupLayout audioLibroLayout = new javax.swing.GroupLayout(audioLibro);
        audioLibro.setLayout(audioLibroLayout);
        audioLibroLayout.setHorizontalGroup(
            audioLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(audioLibroLayout.createSequentialGroup()
                .addGroup(audioLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, audioLibroLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(formato)
                        .addGap(99, 99, 99))
                    .addGroup(audioLibroLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(audioLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator8)
                            .addComponent(textFormato, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))))
                .addGroup(audioLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, audioLibroLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(duracion)
                        .addGap(99, 99, 99))
                    .addGroup(audioLibroLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(audioLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(audioLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peso))
                .addGap(27, 27, 27))
        );
        audioLibroLayout.setVerticalGroup(
            audioLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(audioLibroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(audioLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(audioLibroLayout.createSequentialGroup()
                        .addComponent(peso)
                        .addGap(6, 6, 6)
                        .addComponent(textPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(audioLibroLayout.createSequentialGroup()
                        .addComponent(duracion)
                        .addGap(6, 6, 6)
                        .addComponent(textDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, audioLibroLayout.createSequentialGroup()
                        .addComponent(formato)
                        .addGap(6, 6, 6)
                        .addComponent(textFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        bg.add(audioLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 580, 140));

        libro.setBackground(new java.awt.Color(255, 255, 255));
        libro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 77)), "LIBRO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        libro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                libroMouseEntered(evt);
            }
        });

        noPag.setBackground(new java.awt.Color(255, 255, 255));
        noPag.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        noPag.setText("No PAG");

        textPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textPag.setForeground(new java.awt.Color(204, 204, 204));
        textPag.setText("Ingrese el No PAG...");
        textPag.setBorder(null);
        textPag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textPagMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textPagMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textPagMousePressed(evt);
            }
        });
        textPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPagActionPerformed(evt);
            }
        });
        textPag.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPagKeyTyped(evt);
            }
        });

        edicion.setBackground(new java.awt.Color(255, 255, 255));
        edicion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        edicion.setText("EDICION");

        textEdicion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textEdicion.setForeground(new java.awt.Color(204, 204, 204));
        textEdicion.setText("Ingrese la edicion...");
        textEdicion.setBorder(null);
        textEdicion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textEdicionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textEdicionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textEdicionMousePressed(evt);
            }
        });
        textEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEdicionActionPerformed(evt);
            }
        });
        textEdicion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textEdicionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout libroLayout = new javax.swing.GroupLayout(libro);
        libro.setLayout(libroLayout);
        libroLayout.setHorizontalGroup(
            libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libroLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(noPag)
                    .addComponent(jSeparator5)
                    .addComponent(textPag, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addGap(109, 109, 109)
                .addGroup(libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, libroLayout.createSequentialGroup()
                        .addComponent(edicion)
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, libroLayout.createSequentialGroup()
                        .addGroup(libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(libroLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(textEdicion))
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))))
        );
        libroLayout.setVerticalGroup(
            libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libroLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(libroLayout.createSequentialGroup()
                        .addComponent(edicion)
                        .addGap(6, 6, 6)
                        .addComponent(textEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(libroLayout.createSequentialGroup()
                        .addComponent(noPag)
                        .addGap(6, 6, 6)
                        .addComponent(textPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        bg.add(libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 580, -1));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void textPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPagActionPerformed

    private void textEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEdicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEdicionActionPerformed

    private void textFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFormatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFormatoActionPerformed

    private void textDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDuracionActionPerformed

    private void textPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPesoActionPerformed

    private void botonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseClicked
        boolean vacio = true;
        if (textIsbn.getText().equals("Ingrese el isbn...") || textTitulo.getText().equals("Ingrese el titulo...") || textAutor.getText().equals("Ingrese el autor...") || textAnio.getText().equals("Ingrese el año pub...") || textAnio.getText().equals("Ingrese el año pub...") || textCosto.getText().equals("Ingrese el precio...") || boxTipo.getSelectedItem().equals("Seleccionar Tipo")) {
            JOptionPane.showMessageDialog(null, "complete todas las casillas de informacion.");

        }
        if (boxTipo.getSelectedItem().equals("Libro")) {
            if (textPag.getText().equals("Ingrese el No PAG...") || textEdicion.getText().equals("Ingrese la edicion...")) {
                JOptionPane.showMessageDialog(null, "complete la informacion del libro");
                vacio = true;
            } else {
                vacio = false;
            }
        }
        if (boxTipo.getSelectedItem().equals("Audio Libro")) {
            if (textFormato.getText().equals("Ingrese el formato...") || textDuracion.getText().equals("Ingrese la duracion...") || textPeso.getText().equals("Ingrese el peso...")) {
                JOptionPane.showMessageDialog(null, "complete la informacion del audio libro");
                vacio = true;
            } else {
                vacio = false;
            }
        }
        if (vacio == false) {

            leerNuevaPublicacion();
            registrarPublicacion();
            archivo.textPublicaciones(modelo);

            JOptionPane.showMessageDialog(null, "Datos guardados");

            limpiar();
        }
    }//GEN-LAST:event_botonRegistrarMouseClicked

    private void botonRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistrarMouseEntered

    private void botonRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistrarMouseExited

    private void textIsbnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textIsbnMousePressed

        if (textIsbn.getText().equals("Ingrese el isbn...")) {
            textIsbn.setText("");
            textIsbn.setForeground(Color.black);
        }
        if (String.valueOf(textTitulo.getText()).isEmpty()) {
            textTitulo.setText("Ingrese el titulo...");
            textTitulo.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textAutor.getText()).isEmpty()) {
            textAutor.setText("Ingrese el autor...");
            textAutor.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textAnio.getText()).isEmpty()) {
            textAnio.setText("Ingrese el año pub...");
            textAnio.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textCosto.getText()).isEmpty()) {
            textCosto.setText("Ingrese el precio...");
            textCosto.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textPag.getText()).isEmpty()) {
            textPag.setText("Ingrese el No PAG...");
            textPag.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textEdicion.getText()).isEmpty()) {
            textEdicion.setText("Ingrese la edicion...");
            textEdicion.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textFormato.getText()).isEmpty()) {
            textFormato.setText("Ingrese el formato...");
            textFormato.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textDuracion.getText()).isEmpty()) {
            textDuracion.setText("Ingrese la duracion...");
            textDuracion.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textPeso.getText()).isEmpty()) {
            textPeso.setText("Ingrese el peso...");
            textPeso.setForeground(new Color(204, 204, 204));
        }


    }//GEN-LAST:event_textIsbnMousePressed

    private void textTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textTituloMousePressed
        if (textTitulo.getText().equals("Ingrese el titulo...")) {
            textTitulo.setText("");
            textTitulo.setForeground(Color.black);
        }
        if (String.valueOf(textIsbn.getText()).isEmpty()) {
            textIsbn.setText("Ingrese el isbn...");
            textIsbn.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textAutor.getText()).isEmpty()) {
            textAutor.setText("Ingrese el autor...");
            textAutor.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textAnio.getText()).isEmpty()) {
            textAnio.setText("Ingrese el año pub...");
            textAnio.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textCosto.getText()).isEmpty()) {
            textCosto.setText("Ingrese el precio...");
            textCosto.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textPag.getText()).isEmpty()) {
            textPag.setText("Ingrese el No PAG...");
            textPag.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textEdicion.getText()).isEmpty()) {
            textEdicion.setText("Ingrese la edicion...");
            textEdicion.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textFormato.getText()).isEmpty()) {
            textFormato.setText("Ingrese el formato...");
            textFormato.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textDuracion.getText()).isEmpty()) {
            textDuracion.setText("Ingrese la duracion...");
            textDuracion.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textPeso.getText()).isEmpty()) {
            textPeso.setText("Ingrese el peso...");
            textPeso.setForeground(new Color(204, 204, 204));
        }

    }//GEN-LAST:event_textTituloMousePressed

    private void textAutorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAutorMousePressed
        if (textAutor.getText().equals("Ingrese el autor...")) {
            textAutor.setText("");
            textAutor.setForeground(Color.black);
        }
        if (String.valueOf(textTitulo.getText()).isEmpty()) {
            textTitulo.setText("Ingrese el titulo...");
            textTitulo.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textIsbn.getText()).isEmpty()) {
            textIsbn.setText("Ingrese el isbn...");
            textIsbn.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textAnio.getText()).isEmpty()) {
            textAnio.setText("Ingrese el año pub...");
            textAnio.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textCosto.getText()).isEmpty()) {
            textCosto.setText("Ingrese el precio...");
            textCosto.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textPag.getText()).isEmpty()) {
            textPag.setText("Ingrese el No PAG...");
            textPag.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textEdicion.getText()).isEmpty()) {
            textEdicion.setText("Ingrese la edicion...");
            textEdicion.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textFormato.getText()).isEmpty()) {
            textFormato.setText("Ingrese el formato...");
            textFormato.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textDuracion.getText()).isEmpty()) {
            textDuracion.setText("Ingrese la duracion...");
            textDuracion.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textPeso.getText()).isEmpty()) {
            textPeso.setText("Ingrese el peso...");
            textPeso.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_textAutorMousePressed

    private void textAnioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAnioMousePressed
        if (textAnio.getText().equals("Ingrese el año pub...")) {
            textAnio.setText("");
            textAnio.setForeground(Color.black);
        }
        if (String.valueOf(textTitulo.getText()).isEmpty()) {
            textTitulo.setText("Ingrese el titulo...");
            textTitulo.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textIsbn.getText()).isEmpty()) {
            textIsbn.setText("Ingrese el isbn...");
            textIsbn.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textAutor.getText()).isEmpty()) {
            textAutor.setText("Ingrese el autor...");
            textAutor.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textCosto.getText()).isEmpty()) {
            textCosto.setText("Ingrese el precio...");
            textCosto.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textPag.getText()).isEmpty()) {
            textPag.setText("Ingrese el No PAG...");
            textPag.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textEdicion.getText()).isEmpty()) {
            textEdicion.setText("Ingrese la edicion...");
            textEdicion.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textFormato.getText()).isEmpty()) {
            textFormato.setText("Ingrese el formato...");
            textFormato.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textDuracion.getText()).isEmpty()) {
            textDuracion.setText("Ingrese la duracion...");
            textDuracion.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textPeso.getText()).isEmpty()) {
            textPeso.setText("Ingrese el peso...");
            textPeso.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_textAnioMousePressed

    private void textCostoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textCostoMousePressed
        if (textCosto.getText().equals("Ingrese el precio...")) {
            textCosto.setText("");
            textCosto.setForeground(Color.black);
        }

        if (String.valueOf(textTitulo.getText()).isEmpty()) {
            textTitulo.setText("Ingrese el titulo...");
            textTitulo.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textIsbn.getText()).isEmpty()) {
            textIsbn.setText("Ingrese el isbn...");
            textIsbn.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textAutor.getText()).isEmpty()) {
            textAutor.setText("Ingrese el autor...");
            textAutor.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textAnio.getText()).isEmpty()) {
            textAnio.setText("Ingrese el año pub...");
            textAnio.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textPag.getText()).isEmpty()) {
            textPag.setText("Ingrese el No PAG...");
            textPag.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textEdicion.getText()).isEmpty()) {
            textEdicion.setText("Ingrese la edicion...");
            textEdicion.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textFormato.getText()).isEmpty()) {
            textFormato.setText("Ingrese el formato...");
            textFormato.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textDuracion.getText()).isEmpty()) {
            textDuracion.setText("Ingrese la duracion...");
            textDuracion.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textPeso.getText()).isEmpty()) {
            textPeso.setText("Ingrese el peso...");
            textPeso.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_textCostoMousePressed

    private void boxTipoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxTipoMousePressed
        if (String.valueOf(textTitulo.getText()).isEmpty()) {
            textTitulo.setText("Ingrese el titulo...");
            textTitulo.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textIsbn.getText()).isEmpty()) {
            textIsbn.setText("Ingrese el isbn...");
            textIsbn.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textAutor.getText()).isEmpty()) {
            textAutor.setText("Ingrese el autor...");
            textAutor.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textAnio.getText()).isEmpty()) {
            textAnio.setText("Ingrese el año pub...");
            textAnio.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textPag.getText()).isEmpty()) {
            textPag.setText("Ingrese el No PAG...");
            textPag.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textCosto.getText()).isEmpty()) {
            textCosto.setText("Ingrese el precio...");
            textCosto.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textEdicion.getText()).isEmpty()) {
            textEdicion.setText("Ingrese la edicion...");
            textEdicion.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textFormato.getText()).isEmpty()) {
            textFormato.setText("Ingrese el formato...");
            textFormato.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textDuracion.getText()).isEmpty()) {
            textDuracion.setText("Ingrese la duracion...");
            textDuracion.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textPeso.getText()).isEmpty()) {
            textPeso.setText("Ingrese el peso...");
            textPeso.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_boxTipoMousePressed

    private void textFormatoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFormatoMousePressed
        if (boxTipo.getSelectedItem().equals("Seleccionar Tipo")) {

            textFormato.setText("Ingrese el formato...");
            textFormato.setForeground(new Color(204, 204, 204));

        } else {
            if (textFormato.getText().equals("Ingrese el formato...")) {
                textFormato.setText("");
                textFormato.setForeground(Color.black);
            }
            if (String.valueOf(textTitulo.getText()).isEmpty()) {
                textTitulo.setText("Ingrese el titulo...");
                textTitulo.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textIsbn.getText()).isEmpty()) {
                textIsbn.setText("Ingrese el isbn...");
                textIsbn.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textAutor.getText()).isEmpty()) {
                textAutor.setText("Ingrese el autor...");
                textAutor.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textAnio.getText()).isEmpty()) {
                textAnio.setText("Ingrese el año pub...");
                textAnio.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textPag.getText()).isEmpty()) {
                textPag.setText("Ingrese el No PAG...");
                textPag.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textCosto.getText()).isEmpty()) {
                textCosto.setText("Ingrese el precio...");
                textCosto.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textEdicion.getText()).isEmpty()) {
                textEdicion.setText("Ingrese la edicion...");
                textEdicion.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textDuracion.getText()).isEmpty()) {
                textDuracion.setText("Ingrese la duracion...");
                textDuracion.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textPeso.getText()).isEmpty()) {
                textPeso.setText("Ingrese el peso...");
                textPeso.setForeground(new Color(204, 204, 204));
            }
        }
    }//GEN-LAST:event_textFormatoMousePressed

    private void textDuracionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textDuracionMousePressed
        if (boxTipo.getSelectedItem().equals("Seleccionar Tipo")) {

            textDuracion.setText("Ingrese la duracion...");
            textDuracion.setForeground(new Color(204, 204, 204));

        } else {
            if (textDuracion.getText().equals("Ingrese la duracion...")) {
                textDuracion.setText("");
                textDuracion.setForeground(Color.black);
            }
            if (String.valueOf(textTitulo.getText()).isEmpty()) {
                textTitulo.setText("Ingrese el titulo...");
                textTitulo.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textIsbn.getText()).isEmpty()) {
                textIsbn.setText("Ingrese el isbn...");
                textIsbn.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textAutor.getText()).isEmpty()) {
                textAutor.setText("Ingrese el autor...");
                textAutor.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textAnio.getText()).isEmpty()) {
                textAnio.setText("Ingrese el año pub...");
                textAnio.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textPag.getText()).isEmpty()) {
                textPag.setText("Ingrese el No PAG...");
                textPag.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textCosto.getText()).isEmpty()) {
                textCosto.setText("Ingrese el precio...");
                textCosto.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textEdicion.getText()).isEmpty()) {
                textEdicion.setText("Ingrese la edicion...");
                textEdicion.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textFormato.getText()).isEmpty()) {
                textFormato.setText("Ingrese el formato...");
                textFormato.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textPeso.getText()).isEmpty()) {
                textPeso.setText("Ingrese el peso...");
                textPeso.setForeground(new Color(204, 204, 204));
            }
        }
    }//GEN-LAST:event_textDuracionMousePressed

    private void textPesoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textPesoMousePressed
        if (boxTipo.getSelectedItem().equals("Seleccionar Tipo")) {

            textPeso.setText("Ingrese el peso...");
            textPeso.setForeground(new Color(204, 204, 204));

        } else {
            if (textPeso.getText().equals("Ingrese el peso...")) {
                textPeso.setText("");
                textPeso.setForeground(Color.black);
            }
            if (String.valueOf(textTitulo.getText()).isEmpty()) {
                textTitulo.setText("Ingrese el titulo...");
                textTitulo.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textIsbn.getText()).isEmpty()) {
                textIsbn.setText("Ingrese el isbn...");
                textIsbn.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textAutor.getText()).isEmpty()) {
                textAutor.setText("Ingrese el autor...");
                textAutor.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textAnio.getText()).isEmpty()) {
                textAnio.setText("Ingrese el año pub...");
                textAnio.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textPag.getText()).isEmpty()) {
                textPag.setText("Ingrese el No PAG...");
                textPag.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textCosto.getText()).isEmpty()) {
                textCosto.setText("Ingrese el precio...");
                textCosto.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textEdicion.getText()).isEmpty()) {
                textEdicion.setText("Ingrese la edicion...");
                textEdicion.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textFormato.getText()).isEmpty()) {
                textFormato.setText("Ingrese el formato...");
                textFormato.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textDuracion.getText()).isEmpty()) {
                textDuracion.setText("Ingrese la duracion...");
                textDuracion.setForeground(new Color(204, 204, 204));
            }
        }
    }//GEN-LAST:event_textPesoMousePressed

    private void textPagMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textPagMousePressed
        if (boxTipo.getSelectedItem().equals("Seleccionar Tipo")) {

            textPag.setText("Ingrese el No PAG...");
            textPag.setForeground(new Color(204, 204, 204));

        } else {
            if (textPag.getText().equals("Ingrese el No PAG...")) {
                textPag.setText("");
                textPag.setForeground(Color.black);
            }
            if (String.valueOf(textTitulo.getText()).isEmpty()) {
                textTitulo.setText("Ingrese el titulo...");
                textTitulo.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textIsbn.getText()).isEmpty()) {
                textIsbn.setText("Ingrese el isbn...");
                textIsbn.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textAutor.getText()).isEmpty()) {
                textAutor.setText("Ingrese el autor...");
                textAutor.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textAnio.getText()).isEmpty()) {
                textAnio.setText("Ingrese el año pub...");
                textAnio.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textCosto.getText()).isEmpty()) {
                textCosto.setText("Ingrese el precio...");
                textCosto.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textEdicion.getText()).isEmpty()) {
                textEdicion.setText("Ingrese la edicion...");
                textEdicion.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textFormato.getText()).isEmpty()) {
                textFormato.setText("Ingrese el formato...");
                textFormato.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textDuracion.getText()).isEmpty()) {
                textDuracion.setText("Ingrese la duracion...");
                textDuracion.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textPeso.getText()).isEmpty()) {
                textPeso.setText("Ingrese el peso...");
                textPeso.setForeground(new Color(204, 204, 204));
            }
        }
    }//GEN-LAST:event_textPagMousePressed

    private void textEdicionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEdicionMousePressed
        if (boxTipo.getSelectedItem().equals("Seleccionar Tipo")) {

            textEdicion.setText("Ingrese la edicion...");
            textEdicion.setForeground(new Color(204, 204, 204));

        } else {
            if (textEdicion.getText().equals("Ingrese la edicion...")) {
                textEdicion.setText("");
                textEdicion.setForeground(Color.black);
            }
            if (String.valueOf(textTitulo.getText()).isEmpty()) {
                textTitulo.setText("Ingrese el titulo...");
                textTitulo.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textIsbn.getText()).isEmpty()) {
                textIsbn.setText("Ingrese el isbn...");
                textIsbn.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textAutor.getText()).isEmpty()) {
                textAutor.setText("Ingrese el autor...");
                textAutor.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textAnio.getText()).isEmpty()) {
                textAnio.setText("Ingrese el año pub...");
                textAnio.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textCosto.getText()).isEmpty()) {
                textCosto.setText("Ingrese el precio...");
                textCosto.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textPag.getText()).isEmpty()) {
                textPag.setText("Ingrese el No PAG...");
                textPag.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textFormato.getText()).isEmpty()) {
                textFormato.setText("Ingrese el formato...");
                textFormato.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textDuracion.getText()).isEmpty()) {
                textDuracion.setText("Ingrese la duracion...");
                textDuracion.setForeground(new Color(204, 204, 204));
            }
            if (String.valueOf(textPeso.getText()).isEmpty()) {
                textPeso.setText("Ingrese el peso...");
                textPeso.setForeground(new Color(204, 204, 204));
            }
        }
    }//GEN-LAST:event_textEdicionMousePressed

    private void textIsbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textIsbnKeyTyped
        util.soloNumeros(evt);
    }//GEN-LAST:event_textIsbnKeyTyped

    private void textTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTituloKeyTyped
        if (textTitulo.getText().isEmpty()) {
            util.letrasYnumeros(evt);
        } else {
            util.lestrasYnumerosYespacios(evt);
        }

    }//GEN-LAST:event_textTituloKeyTyped

    private void textAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAutorKeyTyped
        if (textAutor.getText().isEmpty()) {
            util.letrasYnumeros(evt);
        } else {
            util.lestrasYnumerosYespacios(evt);
        }
    }//GEN-LAST:event_textAutorKeyTyped

    private void textAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAnioKeyTyped
        util.soloNumeros(evt);
    }//GEN-LAST:event_textAnioKeyTyped

    private void textCostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCostoKeyTyped
        util.soloNumeros(evt);
    }//GEN-LAST:event_textCostoKeyTyped

    private void textPagKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPagKeyTyped
        util.soloNumeros(evt);
    }//GEN-LAST:event_textPagKeyTyped

    private void textEdicionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textEdicionKeyTyped
        util.soloNumeros(evt);
    }//GEN-LAST:event_textEdicionKeyTyped

    private void textFormatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFormatoKeyTyped
        util.letrasYnumeros(evt);
    }//GEN-LAST:event_textFormatoKeyTyped

    private void textDuracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDuracionKeyTyped
        util.soloNumeros(evt);
    }//GEN-LAST:event_textDuracionKeyTyped

    private void textPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPesoKeyTyped
        util.soloNumeros(evt);
    }//GEN-LAST:event_textPesoKeyTyped

    private void boxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTipoActionPerformed
        if (boxTipo.getSelectedItem().equals("Seleccionar Tipo")) {
            util.deshabilitarPanel(libro);
            util.deshabilitarPanel(audioLibro);
            //--------------------
            textEdicion.setText("Ingrese la edicion...");
            textEdicion.setForeground(new Color(204, 204, 204));
            //---------------------
            textPag.setText("Ingrese el No PAG...");
            textPag.setForeground(new Color(204, 204, 204));
            //---------------------
            textPeso.setText("Ingrese el peso...");
            textPeso.setForeground(new Color(204, 204, 204));
            //---------------------
            textFormato.setText("Ingrese el formato...");
            textFormato.setForeground(new Color(204, 204, 204));
            //---------------------
            textDuracion.setText("Ingrese la duracion...");
            textDuracion.setForeground(new Color(204, 204, 204));
        }
        if (boxTipo.getSelectedItem().equals("Libro")) {
            //mostrar panel libro
            audioLibro.setVisible(false);
            libro.setVisible(true);

            //habilitar panel libro
            util.habilitarPanel(libro);
        }
        
        if (boxTipo.getSelectedItem().equals("Audio Libro")) {
            //mostrar el panel audio libro
            libro.setVisible(false);
            audioLibro.setVisible(true);

            //habilitar el panel del libro
            util.habilitarPanel(audioLibro);
        }
    }//GEN-LAST:event_boxTipoActionPerformed

    private void bgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseClicked
        reestablecer();
    }//GEN-LAST:event_bgMouseClicked

    private void informacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacionMouseClicked
        reestablecer();
    }//GEN-LAST:event_informacionMouseClicked

    private void libroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libroMouseClicked
        reestablecer();
    }//GEN-LAST:event_libroMouseClicked

    private void textTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTituloActionPerformed

    private void textIsbnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textIsbnMouseClicked

    }//GEN-LAST:event_textIsbnMouseClicked

    private void textIsbnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textIsbnMouseEntered
        habilitarTab(textIsbn);

    }//GEN-LAST:event_textIsbnMouseEntered

    private void textTituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textTituloMouseEntered

        habilitarTab(textTitulo);

    }//GEN-LAST:event_textTituloMouseEntered

    private void textTituloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textTituloMouseExited

    }//GEN-LAST:event_textTituloMouseExited

    private void textTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textTituloMouseClicked


    }//GEN-LAST:event_textTituloMouseClicked

    private void textIsbnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textIsbnMouseExited

    }//GEN-LAST:event_textIsbnMouseExited

    private void informacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacionMouseEntered
        tabPaneles();
    }//GEN-LAST:event_informacionMouseEntered

    private void textAutorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAutorMouseEntered
        habilitarTab(textAutor);
    }//GEN-LAST:event_textAutorMouseEntered

    private void textAutorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAutorMouseExited

    }//GEN-LAST:event_textAutorMouseExited

    private void textAnioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAnioMouseEntered
        habilitarTab(textAnio);
    }//GEN-LAST:event_textAnioMouseEntered

    private void textAnioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAnioMouseExited

    }//GEN-LAST:event_textAnioMouseExited

    private void textCostoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textCostoMouseEntered
        habilitarTab(textCosto);
    }//GEN-LAST:event_textCostoMouseEntered

    private void textCostoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textCostoMouseExited

    }//GEN-LAST:event_textCostoMouseExited

    private void textPagMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textPagMouseEntered
        habilitarTab(textPag);
    }//GEN-LAST:event_textPagMouseEntered

    private void textPagMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textPagMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_textPagMouseExited

    private void textEdicionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEdicionMouseEntered
        habilitarTab(textEdicion);
    }//GEN-LAST:event_textEdicionMouseEntered

    private void textEdicionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEdicionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_textEdicionMouseExited

    private void textFormatoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFormatoMouseEntered
        habilitarTab(textFormato);
    }//GEN-LAST:event_textFormatoMouseEntered

    private void textFormatoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFormatoMouseExited

    }//GEN-LAST:event_textFormatoMouseExited

    private void textDuracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textDuracionMouseEntered
        habilitarTab(textDuracion);
    }//GEN-LAST:event_textDuracionMouseEntered

    private void textDuracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textDuracionMouseExited

    }//GEN-LAST:event_textDuracionMouseExited

    private void textPesoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textPesoMouseEntered
        habilitarTab(textPeso);
    }//GEN-LAST:event_textPesoMouseEntered

    private void textPesoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textPesoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_textPesoMouseExited

    private void audioLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_audioLibroMouseEntered
        tabPaneles();
    }//GEN-LAST:event_audioLibroMouseEntered

    private void libroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libroMouseEntered
        tabPaneles();
    }//GEN-LAST:event_libroMouseEntered

    private void audioLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_audioLibroMouseClicked
        reestablecer();
    }//GEN-LAST:event_audioLibroMouseClicked

    private void habilitarTab(JTextField text) {
        text.setFocusable(true);
    }
    private void deshabilitarTab() {
        textIsbn.setFocusable(false);
        textTitulo.setFocusable(false);
        textAutor.setFocusable(false);
        textAnio.setFocusable(false);
        textCosto.setFocusable(false);
        textPag.setFocusable(false);
        textEdicion.setFocusable(false);
        textFormato.setFocusable(false);
        textDuracion.setFocusable(false);
        textPeso.setFocusable(false);
        boxTipo.setFocusable(false);
    }

    private void tabPaneles() {

        if (textIsbn.getText().equals("Ingrese el isbn...")) {
            textIsbn.setFocusable(false);
        }

        if (textTitulo.getText().equals("Ingrese el titulo...")) {
            textTitulo.setFocusable(false);
        }

        if (textAutor.getText().equals("Ingrese el autor...")) {
            textAutor.setFocusable(false);
        }

        if (textAnio.getText().equals("Ingrese el año pub...")) {
            textAnio.setFocusable(false);
        }

        if (textCosto.getText().equals("Ingrese el precio...")) {
            textCosto.setFocusable(false);
        }

        if (textPag.getText().equals("Ingrese el No PAG...")) {
            textPag.setFocusable(false);
        }

        if (textEdicion.getText().equals("Ingrese la edicion...")) {
            textEdicion.setFocusable(false);
        }

        if (textFormato.getText().equals("Ingrese el formato...")) {
            textFormato.setFocusable(false);
        }

        if (textDuracion.getText().equals("Ingrese la duracion...")) {
            textDuracion.setFocusable(false);
        }

        if (textPeso.getText().equals("Ingrese el peso...")) {
            textPeso.setFocusable(false);
        }

    }
    
    private void reestablecer() {
        if (String.valueOf(textFormato.getText()).isEmpty()) {
            textFormato.setText("Ingrese el formato...");
            textFormato.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textTitulo.getText()).isEmpty()) {
            textTitulo.setText("Ingrese el titulo...");
            textTitulo.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textIsbn.getText()).isEmpty()) {
            textIsbn.setText("Ingrese el isbn...");
            textIsbn.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textAutor.getText()).isEmpty()) {
            textAutor.setText("Ingrese el autor...");
            textAutor.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textAnio.getText()).isEmpty()) {
            textAnio.setText("Ingrese el año pub...");
            textAnio.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textPag.getText()).isEmpty()) {
            textPag.setText("Ingrese el No PAG...");
            textPag.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textCosto.getText()).isEmpty()) {
            textCosto.setText("Ingrese el precio...");
            textCosto.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textEdicion.getText()).isEmpty()) {
            textEdicion.setText("Ingrese la edicion...");
            textEdicion.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textDuracion.getText()).isEmpty()) {
            textDuracion.setText("Ingrese la duracion...");
            textDuracion.setForeground(new Color(204, 204, 204));
        }
        if (String.valueOf(textPeso.getText()).isEmpty()) {
            textPeso.setText("Ingrese el peso...");
            textPeso.setForeground(new Color(204, 204, 204));
        }

        deshabilitarTab();
    }

    private void limpiar() {
        textFormato.setText("Ingrese el formato...");
        textFormato.setForeground(new Color(204, 204, 204));

        textTitulo.setText("Ingrese el titulo...");
        textTitulo.setForeground(new Color(204, 204, 204));

        textIsbn.setText("Ingrese el isbn...");
        textIsbn.setForeground(new Color(204, 204, 204));

        textAutor.setText("Ingrese el autor...");
        textAutor.setForeground(new Color(204, 204, 204));

        textAnio.setText("Ingrese el año pub...");
        textAnio.setForeground(new Color(204, 204, 204));

        textPag.setText("Ingrese el No PAG...");
        textPag.setForeground(new Color(204, 204, 204));

        textCosto.setText("Ingrese el precio...");
        textCosto.setForeground(new Color(204, 204, 204));

        textEdicion.setText("Ingrese la edicion...");
        textEdicion.setForeground(new Color(204, 204, 204));

        textDuracion.setText("Ingrese la duracion...");
        textDuracion.setForeground(new Color(204, 204, 204));

        textPeso.setText("Ingrese el peso...");
        textPeso.setForeground(new Color(204, 204, 204));

        boxTipo.setSelectedIndex(0);
        deshabilitarTab();
    }

    public void registrarPublicacion() {
        Publicacion nuevaPublicacion = this.leerNuevaPublicacion();
        this.modelo.insertarPublicacion(nuevaPublicacion);
    }

    public Publicacion leerNuevaPublicacion() {

        String isbn = textIsbn.getText();
        String titulo = textTitulo.getText();
        String autor = textAutor.getText();
        int anio = Integer.parseInt(textAnio.getText());
        double costo = Double.parseDouble(textCosto.getText());
        int tipo = boxTipo.getSelectedIndex();

        if (tipo == 1) {
            int nPag = Integer.parseInt(textPag.getText());
            int edicion = Integer.parseInt(textEdicion.getText());

            publicacion = new Libro(nPag, edicion, isbn, titulo, autor, anio, costo);
        }
        if (tipo == 2) {
            String formato = textFormato.getText();
            double duracion = Double.parseDouble(textDuracion.getText());
            double peso = Double.parseDouble(textPeso.getText());
            publicacion = new AudioLibro(duracion, peso, formato, isbn, titulo, autor, anio, costo);
        }
        return publicacion;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anio;
    private javax.swing.JPanel audioLibro;
    private javax.swing.JLabel autor;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel botonRegistrar;
    private javax.swing.JComboBox<String> boxTipo;
    private javax.swing.JLabel costo;
    private javax.swing.JLabel duracion;
    private javax.swing.JLabel edicion;
    private javax.swing.JLabel formato;
    private javax.swing.JPanel informacion;
    private javax.swing.JLabel isbn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel libro;
    private javax.swing.JLabel noPag;
    private javax.swing.JLabel peso;
    private javax.swing.JTextField textAnio;
    private javax.swing.JTextField textAutor;
    private javax.swing.JTextField textCosto;
    private javax.swing.JTextField textDuracion;
    private javax.swing.JTextField textEdicion;
    private javax.swing.JTextField textFormato;
    private javax.swing.JTextField textIsbn;
    private javax.swing.JTextField textPag;
    private javax.swing.JTextField textPeso;
    private javax.swing.JTextField textTitulo;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
