/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unicesar.vista;

import co.edu.unicesar.persistencia.ArchivoTxt;
import co.edu.unicesar.utilidades.Interfaz;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */

public class PanelInicio extends javax.swing.JPanel {

    

    /** Creates new form PanelInicio */
    private PanelInsertar insertar1;
    private PanelConsultar consul1;
    private Interfaz util;
    public ArchivoTxt util2;
    
    public PanelInicio() {
        
        initComponents();
        
        insertar1 = new PanelInsertar();
        consul1 = new PanelConsultar();
        util = new Interfaz();
        util2 = new ArchivoTxt();
        contenedor.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonlRegistrar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        botonSalir = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        botonConsultar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        contenedor1 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("BIENVENIDO");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(43, 42, 77), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("MENU");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 12, -1, -1));

        botonlRegistrar.setBackground(new java.awt.Color(43, 42, 77));
        botonlRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonlRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonlRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonlRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonlRegistrarMouseExited(evt);
            }
        });
        botonlRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REGISTRAR");
        botonlRegistrar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jPanel2.add(botonlRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, 90));

        botonSalir.setBackground(new java.awt.Color(43, 42, 77));
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSalirMouseExited(evt);
            }
        });
        botonSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SALIR");
        botonSalir.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jPanel2.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 210, 90));

        botonConsultar.setBackground(new java.awt.Color(43, 42, 77));
        botonConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonConsultarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonConsultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonConsultarMouseExited(evt);
            }
        });
        botonConsultar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONSULTAR");
        botonConsultar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jPanel2.add(botonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 210, 90));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1))
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        contenedor1.setBackground(new java.awt.Color(255, 255, 255));
        contenedor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout contenedor1Layout = new javax.swing.GroupLayout(contenedor1);
        contenedor1.setLayout(contenedor1Layout);
        contenedor1Layout.setHorizontalGroup(
            contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        contenedor1Layout.setVerticalGroup(
            contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        add(contenedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));
    }// </editor-fold>//GEN-END:initComponents

    //boton registrar
    private void botonlRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonlRegistrarMouseClicked
        util.showPanel(contenedor1,VistaInterfaz.insertar);
        VistaInterfaz.consul.limpiar();
        activarPanel();
    }//GEN-LAST:event_botonlRegistrarMouseClicked

    private void botonlRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonlRegistrarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonlRegistrarMouseEntered

    private void botonlRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonlRegistrarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonlRegistrarMouseExited

    //boton consultar
    private void botonConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConsultarMouseClicked
        util.showPanel(contenedor1,VistaInterfaz.consul);
        util2.datosText(PanelConsultar.modelo_tabla);;
        activarPanel();
    }//GEN-LAST:event_botonConsultarMouseClicked

    private void botonConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConsultarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConsultarMouseEntered

    private void botonConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConsultarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConsultarMouseExited
   
    //boton salir
    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseClicked
        String arreglo[] = {"Si","No"};
        int opcion = JOptionPane.showOptionDialog(null, "¿Desea salir?", "Salir", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo, "");
        if(opcion==0){
            System.exit(0);
        }
    }//GEN-LAST:event_botonSalirMouseClicked

    private void botonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirMouseEntered

    private void botonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirMouseExited
   
    public void activarPanel(){
        contenedor.setVisible(false);
         contenedor1.setVisible(true);
    }
    
    public void run(){
        contenedor1.setVisible(false);
        contenedor.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonConsultar;
    private javax.swing.JPanel botonSalir;
    private javax.swing.JPanel botonlRegistrar;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel contenedor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

   

}
