/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unicesar.vista;


import co.edu.unicesar.persistencia.ArchivoTxt;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class VistaInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form VistaInterfaz
     */
    int xMouse, yMouse;
    public static PanelInsertar insertar;
    public static PanelConsultar consul;
    private PanelInicio inicio;
    public ArchivoTxt util;
    
    public VistaInterfaz() {
        initComponents();
        setLocationRelativeTo(null);
        inicio = new PanelInicio();
        insertar = new PanelInsertar();
        consul = new PanelConsultar();
        util = new ArchivoTxt();
        showPanel(inicio);
        util.limpiarText();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        exitP = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botonInicio = new javax.swing.JPanel();
        textInicio = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JPanel();
        textRegistrar = new javax.swing.JLabel();
        botonConsultar = new javax.swing.JPanel();
        textConsultar = new javax.swing.JLabel();
        botonSalir = new javax.swing.JPanel();
        textSalir = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        head = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(43, 42, 77));
        menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitP.setBackground(new java.awt.Color(43, 42, 77));
        exitP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitPMouseExited(evt);
            }
        });

        cerrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cerrar.setForeground(new java.awt.Color(204, 204, 204));
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setText("X");

        javax.swing.GroupLayout exitPLayout = new javax.swing.GroupLayout(exitP);
        exitP.setLayout(exitPLayout);
        exitPLayout.setHorizontalGroup(
            exitPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        exitPLayout.setVerticalGroup(
            exitPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        menu.add(exitP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");
        menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        botonInicio.setBackground(new java.awt.Color(43, 42, 77));
        botonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonInicioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonInicioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botonInicioMouseReleased(evt);
            }
        });
        botonInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textInicio.setForeground(new java.awt.Color(255, 255, 255));
        textInicio.setText("INICIO");
        botonInicio.add(textInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 12, -1, -1));

        menu.add(botonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 170, 40));

        botonRegistrar.setBackground(new java.awt.Color(43, 42, 77));
        botonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistrarMouseExited(evt);
            }
        });

        textRegistrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        textRegistrar.setText("REGISTRAR");

        javax.swing.GroupLayout botonRegistrarLayout = new javax.swing.GroupLayout(botonRegistrar);
        botonRegistrar.setLayout(botonRegistrarLayout);
        botonRegistrarLayout.setHorizontalGroup(
            botonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonRegistrarLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(textRegistrar)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        botonRegistrarLayout.setVerticalGroup(
            botonRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textRegistrar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        menu.add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 170, 40));

        botonConsultar.setBackground(new java.awt.Color(43, 42, 77));
        botonConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonConsultarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonConsultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonConsultarMouseExited(evt);
            }
        });

        textConsultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textConsultar.setForeground(new java.awt.Color(255, 255, 255));
        textConsultar.setText("CONSULTAR");

        javax.swing.GroupLayout botonConsultarLayout = new javax.swing.GroupLayout(botonConsultar);
        botonConsultar.setLayout(botonConsultarLayout);
        botonConsultarLayout.setHorizontalGroup(
            botonConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonConsultarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(textConsultar)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        botonConsultarLayout.setVerticalGroup(
            botonConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonConsultarLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(textConsultar)
                .addContainerGap())
        );

        menu.add(botonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 170, 40));

        botonSalir.setBackground(new java.awt.Color(43, 42, 77));
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSalirMouseExited(evt);
            }
        });

        textSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textSalir.setForeground(new java.awt.Color(255, 255, 255));
        textSalir.setText("SALIR");

        javax.swing.GroupLayout botonSalirLayout = new javax.swing.GroupLayout(botonSalir);
        botonSalir.setLayout(botonSalirLayout);
        botonSalirLayout.setHorizontalGroup(
            botonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonSalirLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(textSalir)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        botonSalirLayout.setVerticalGroup(
            botonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textSalir)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        menu.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 170, 40));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 480));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 600, 480));

        head.setBackground(new java.awt.Color(43, 42, 77));
        head.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headMouseDragged(evt);
            }
        });
        head.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headLayout = new javax.swing.GroupLayout(head);
        head.setLayout(headLayout);
        headLayout.setHorizontalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        headLayout.setVerticalGroup(
            headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 740, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPMouseClicked
        String arreglo[] = {"Si","No"};
        int opcion = JOptionPane.showOptionDialog(null, "¿Desea salir?", "Salir", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo, "");
        if(opcion==0){
            System.exit(0);
        }
    }//GEN-LAST:event_exitPMouseClicked

    private void exitPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPMouseEntered
        exitP.setBackground(Color.red);
    }//GEN-LAST:event_exitPMouseEntered

    private void exitPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPMouseExited
        exitP.setBackground(new Color(43,42,77));
    }//GEN-LAST:event_exitPMouseExited

    //boton incio
    private void botonInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseClicked
        showPanel(inicio);
        inicio.run();
        consul.limpiar();
    }//GEN-LAST:event_botonInicioMouseClicked

    private void botonInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseEntered
        botonInicio.setBackground(Color.WHITE);
        textInicio.setForeground(Color.BLACK);
    }//GEN-LAST:event_botonInicioMouseEntered

    private void botonInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseExited
        botonInicio.setBackground(new Color(43,42,77));
        textInicio.setForeground(Color.WHITE);
    }//GEN-LAST:event_botonInicioMouseExited

    //boton registrar
    private void botonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseClicked
        showPanel(insertar);
        consul.limpiar();
    }//GEN-LAST:event_botonRegistrarMouseClicked

    private void botonRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseEntered
        botonRegistrar.setBackground(Color.WHITE);
        textRegistrar.setForeground(Color.BLACK);
    }//GEN-LAST:event_botonRegistrarMouseEntered

    private void botonRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarMouseExited
        botonRegistrar.setBackground(new Color(43,42,77));
        textRegistrar.setForeground(Color.WHITE);
    }//GEN-LAST:event_botonRegistrarMouseExited

    //boton consultar
    private void botonConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConsultarMouseClicked
        showPanel(consul);
        consul.limpiar();
        util.datosText(PanelConsultar.modelo_tabla);
    }//GEN-LAST:event_botonConsultarMouseClicked

    private void botonConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConsultarMouseEntered
        botonConsultar.setBackground(Color.WHITE);
        textConsultar.setForeground(Color.BLACK);
    }//GEN-LAST:event_botonConsultarMouseEntered

    private void botonConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConsultarMouseExited
        botonConsultar.setBackground(new Color(43,42,77));
        textConsultar.setForeground(Color.WHITE);
    }//GEN-LAST:event_botonConsultarMouseExited

    //boton salir
    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseClicked
        String arreglo[] = {"Si","No"};
        int opcion = JOptionPane.showOptionDialog(null, "¿Desea salir?", "Salir", 0, JOptionPane.QUESTION_MESSAGE, null, arreglo, "");
        if(opcion==0){
            System.exit(0);
        }
    }//GEN-LAST:event_botonSalirMouseClicked

    private void botonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseEntered
        botonSalir.setBackground(Color.WHITE);
        textSalir.setForeground(Color.BLACK);
    }//GEN-LAST:event_botonSalirMouseEntered

    private void botonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseExited
        botonSalir.setBackground(new Color(43,42,77));
        textSalir.setForeground(Color.WHITE);
    }//GEN-LAST:event_botonSalirMouseExited

    private void headMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headMouseDragged

    private void headMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headMousePressed

    private void botonInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMousePressed
        
    }//GEN-LAST:event_botonInicioMousePressed

    private void botonInicioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseReleased
        
    }//GEN-LAST:event_botonInicioMouseReleased

   
    public static void showPanel(JPanel p){
         p.setSize(600,480);
         p.setLocation(0, 0);
         
         content.removeAll();
         content.add(p, BorderLayout.CENTER);
         content.revalidate();
         content.repaint();
    }
    
    public void run() {
        new VistaInterfaz().setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonConsultar;
    private javax.swing.JPanel botonInicio;
    private javax.swing.JPanel botonRegistrar;
    private javax.swing.JPanel botonSalir;
    private javax.swing.JLabel cerrar;
    private static javax.swing.JPanel content;
    private javax.swing.JPanel exitP;
    private javax.swing.JPanel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel textConsultar;
    private javax.swing.JLabel textInicio;
    private javax.swing.JLabel textRegistrar;
    private javax.swing.JLabel textSalir;
    // End of variables declaration//GEN-END:variables

}
